version: '1.0' # Version number for this config

data-api-pipeline: 
  data-file-location: API-Pipeline_last_run # no slashes before or after! One directory, not a tree.

database:
  connection-string-template: DRIVER={ODBC Driver 18 for SQL Server};SERVER={{database-server}};DATABASE={{database-name}};Trusted_Connection=yes;Encrypt=no; # Known variables: database-server, database-name, database-user, database-password
  type: SQL-Server

concept-glossary:
  type: 'None' # 'None' if no concept glossary is present.

latest:
    name: 'nustada'
    relative-path: 'DataAPI' # No slashes before or after!

history:
  snapshot-date-column: 'sogu_dagur'
  snapshot-database: 'Dapi-Demo-API-Private' # Optional. Where the snapshots will be created. Views will always be in the public part.
  projects:
    - project:
        source-schema: 'nustada'
        snapshot-schema: 'snapshot'
        public-schema: 'saga'
    
# Used for both documentation creation and validation (BG/DD/dbt models)
public-schemas: # Schemas need to be case-correct
  - 'nustada'
  - 'saga'
  
documentation:
    publish-to: 'Confluence' # Only supported target right now! See the data-api-pipeline.env template for variables!
    data-health-report:
      generate: True
      publish: False
    definition-health-report:
      generate: True
      publish: False
    user-documentation:
      generate: True
      publish: False

audit: 
  enabled: True
  database: Dapi-Demo-API-Private
  schema: audit

log-level: 'debug' # debug, warning, info, error, critical