version: 2

sources:
  - name: byggdastofnun
    database: "{{ env_var('DAPI_PRIVATE_DATABASE_INSTANCE') }}"
    schema: "{{ var('byggdastofnun-staging') }}"
    tables:
      - name: thjonustukortagogn